package com.Wsdl2Code.WebServices.Users;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 11/27/2014 8:36:21 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import java.util.Hashtable;
import java.util.Vector;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;

public class VectorUsers extends Vector<Users> implements KvmSerializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -46303249525667101L;

	public VectorUsers() {
	}

	public VectorUsers(SoapObject soapObject) {
		if (soapObject == null)
			return;
		if (soapObject != null) {
			int size = soapObject.getPropertyCount();
			for (int i0 = 0; i0 < size; i0++) {
				Object obj = soapObject.getProperty(i0);
				if (obj != null && obj.getClass().equals(SoapObject.class)) {
					SoapObject j0 = (SoapObject) soapObject.getProperty(i0);
					Users j1 = new Users(j0);
					add(j1);
				}
			}
		}
	}

	@Override
	public Object getProperty(int arg0) {
		return this.get(arg0);
	}

	@Override
	public int getPropertyCount() {
		return this.size();
	}

	@Override
	public void getPropertyInfo(int index,
			@SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
		info.name = "users";
		info.type = Users.class;
	}

	@Override
	public void setProperty(int arg0, Object arg1) {
	}

}
